apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-web-server
  template:
    metadata:
      labels:
        app: hello-world-web-server
    spec:
      containers:
      - name: hello-world-web-server
        image: nginx:alpine
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-c", "echo 'Hello World' > /usr/share/nginx/html/index.html; nginx -g 'daemon off;'"]
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-web-server
spec:
  selector:
    app: hello-world-web-server
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
